adding a yml
HTR-United/htr-united pull request #12
Opened 2021-02-26 18:44 UTC by alix-tz

solving #1

2021-02-26 18:45 UTC, alix-tz commented
@PonteIneptique  Est-ce que ça te semble aller cette première version du fichier yml ?

2021-02-27 07:12 UTC, PonteIneptique requested changes
Un petit changement et des questions :)

2021-02-27 07:12 UTC, PonteIneptique commented on htr-united.yml
> +            - {count: "150", metric: data.metric}
data.metric n'a pas été remplacé. Je suppose que c'est page ici :)

2021-02-27 07:12 UTC, PonteIneptique commented on htr-united.yml
> +        id: '00000001'
Je me demande dans quelle mesure l'id peut être égal à l'URL ici.
Gérer des ID incrémentaux va être galère...

2021-03-08 17:07 UTC, alix-tz commented on htr-united.yml
> +        id: '00000001'
Je suis d'accord avec toi pour les ID, on supprime !

2021-03-08 17:10 UTC, alix-tz commented on htr-united.yml
> +            - {count: "150", metric: data.metric}
je rectifie à la main, mais j'ai ouvert une issue pour qu'on pense à corriger le bug dans le formulaire

2021-03-08 17:16 UTC, alix-tz reviewed
changes made!

2021-03-22 14:53 UTC, alix-tz commented
@PonteIneptique peux-tu valider la PR si elle est bonne suite aux changements que j'ai fait ? :rocket:

2021-03-22 15:08 UTC, PonteIneptique commented
Oups pardon.
Je crois que pages doit être entre `"` normalement... Je merge et quand tu as le temps tu reviens dessus ? Ça passe chez certains parseurs.

2021-03-22 15:09 UTC, merged